version: '3.8'

services:
  octra-wallet:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: octra-wallet
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - octra-network

  # Optional: Add nginx as separate service for more control
  nginx:
    image: nginx:alpine
    container_name: octra-wallet-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # Mount SSL certificates
    depends_on:
      - octra-wallet
    networks:
      - octra-network

networks:
  octra-network:
    driver: bridge